### ISSUE TITLE
"UpdateManyMutationInput" empty for a joining table

### ISSUE THREAD

**Issue by lukigarazus** [MichalLytek/typegraphql-prisma#36] opened 2020-11-24 14:02 UTC
I have a simple app with the following Prisma schema:

```
model TodoViewTodo {
  id          Int      @id @default(autoincrement())
  todo        Int
  todoView    Int
  placeholder String?
  Todo        Todo     @relation(fields: [todo], references: [id])
  TodoView    TodoView @relation(fields: [todoView], references: [id])
}

model Todo {
  id           Int            @id @default(autoincrement())
  text         String
  done         Boolean?
  user         Int
  User         User           @relation(fields: [user], references: [id])
  TodoViewTodo TodoViewTodo[]
}

model TodoView {
  id           Int            @id @default(autoincrement())
  label        String
  order        String?
  color        String
  TodoViewTodo TodoViewTodo[]
}
```

When I generate a schema using `typegraphql-prisma` resolvers and `buildSchema` I get an empty input:
```
input TodoViewTodoUpdateManyMutationInput
```
which causes all GraphQL operations to fail due to an invalid schema.

I had to add the `placeholder` field for this input not to be empty, which is not ideal.

**Comment by MichalLytek** [comment] 2020-11-24 14:07
Duplicate of #19 🔒

**Closed by MichalLytek** 2020-11-24 14:07 UTC
