### ISSUE TITLE
rejectOnNotFound throws Error when non-required relation is null

### ISSUE THREAD

**Issue by rtnolan** [MichalLytek/typegraphql-prisma#169] opened 2021-08-25 09:07 UTC
**Describe the Bug**
I'm attempting to throw an Error when findUnique() doesn't return a value for a given model. However when a relation on that model is null (it's not required) I'm getting an error back in `Errors`. My Prisma schema looks like:

```prisma
model User {
  id     String @id @default(cuid())
  email  String @unique
  infoId String? @unique
  Info   Info?  @relation(fields: [infoId], references: [id])
}

model Info {
  id   String @id @default(cuid())
  User User?
}
```
Prisma Client:
```javascript
const prisma = new PrismaClient({
  rejectOnNotFound: {
    findUnique: {
      User: (err) => new Error("Could not find user."),
    },
  },
});
```
**To Reproduce**
I have a sample repo here: https://github.com/tnolan8/urql-prisma which has a Readme attached.

**Expected Behavior**
I would not expect there to be any Errors when a non-required relation is null when the Prisma Client is configured to only throw an Error when it's parent is null.

**Logs**
```json
{
  "errors": [
    {
      "message": "Could not find user.",
      "locations": [{ "line": 12, "column": 5 }],
      "path": ["getUser", "Info"],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "clientVersion": "2.29.0",
          "stacktrace": [
            "Error: Could not find user.",
            "..."
          ]
        }
      }
    }
  ],
  "data": {
    "getUser": {
      "id": "ckfqy3w2q022813mawgzib8x4",
      "email": "test123@gmail.com",
      "Info": null,
      "__typename": "User"
    }
  }
}
```
Here you can see that it returns the User correctly but also returns an Error.

**Environment (please complete the following information):**

- OS: MacOS Big Sur 11.5.1
- Node 14.15.1
- `typegraphql-prisma` version 0.14.8
- Prisma version 2.29.0
- TypeScript version 4.3.5

**Comment by MichalLytek** [comment] 2021-08-25 09:57
Please raise that issue on the Prisma side. 

`typegraphql-prisma`, uses `.findUnique()` without `rejectOnNotFound: true` argument, so I can do nothing about it.

**Comment by tnolan8** [comment] 2021-08-25 10:00
So I originally started a discussion on the Prisma repo, but the actual `.findUnique()` works fine when I'm not using it with TypeGraphQL. In the example repo above I set up a simple server without TypeGraphQL and it works fine, it's just when I use the default resolvers generated by TypeGraphQL that the problem arises.

**Comment by tnolan8** [comment] 2021-08-25 10:04
Sorry I miss-read, your comment. So the issue is on the Prisma side?

**Comment by MichalLytek** [comment] 2021-08-25 10:16
You are resolving relations by using `include` in `findUnique`, which is a wrong approach in GraphQL ecosystem:
```ts
const user = await ctx.prisma.user.findUnique({
  where: { id: args.where.id },
  include: { Info: true },
});
```

`typegraphql-prisma` has dedicated type field resolvers which are resolving the relations, which is doing this:
```ts
return prisma.user.findUnique({
  where: { id: parent.id },
}).posts();
```

So looks like your global `rejectOnNotFound` setting is forcing all `.findUnique()` calls to throw error, instead of only swapping the thrown errors.

**Comment by tnolan8** [comment] 2021-08-25 10:25
Okay I understand now. So the Field Resolver that resolves the relation between the User and Info model needs some way of knowing not to throw an Error if it resolves too null. I'll open an issue over on Prisma. Cheers @MichalLytek 👋

**Comment by MichalLytek** [comment] 2021-08-25 10:30
Try running this one on your Prisma client:

```ts
const prisma = new PrismaClient({
  rejectOnNotFound: {
    findUnique: {
      User: (err) => new Error("Could not find user."),
    },
  },
});

// expect to throw error
await prisma.user.findUnique({
  where: { id: "ckqjgja0b0009rxtp2b0avh92" },
  rejectOnNotFound: true,
});

// expect to not throw anything
await prisma.user.findUnique({
  where: { id: "ckqjgja0b0009rxtp2b0avh92" },
  rejectOnNotFound: true,
});

// expect to not throw anything
await prisma.user.findUnique({
  where: { id: "ckqjgja0b0009rxtp2b0avh92" },
});
```

**Comment by tnolan8** [comment] 2021-08-25 10:38
Yeah so, 1 throws an Error, 2 doesn't, 3 does. It seems that if a relation resolves to Null when I call `await prisma.user.findUnique({..})` then it throws an Error. Using `include` gets around it like you said but I'll go back to my discussion on the Prisma repo and see if there's anything else I can do.

**Comment by MichalLytek** [comment] 2021-08-25 10:40
I could put `rejectOnNotFound: false` everywhere in the resolvers but I think Prisma should fix that on their side, so that the default behavior is not affected.

**Comment by tnolan8** [comment] 2021-08-25 10:45
I'll mention the issue here once I get it created, thanks for the help again. 👍

**Comment by MichalLytek** [comment] 2021-11-10 12:38
Closing for a housekeeping purposes 🔒 The fix from Prisma will propagate to `typegraphql-prisma` with a dependency bump.

**Closed by MichalLytek** 2021-11-10 12:38 UTC
Labels: out of scope
