### ISSUE TITLE
Genrating typegraphql resolvers stopped working in yarn2 after 0.13.0 update

### ISSUE THREAD

**Issue by Unbuttun** [MichalLytek/typegraphql-prisma#95] opened 2021-04-08 09:01 UTC
**Describe the Bug**
When I do `prisma generate` after upgrading all prisma related dependencies to latest version, the generation of typegraphql keeps going out infinitely.

**To Reproduce**
https://github.com/Unbuttun/Olympus/tree/dev 

1. Clone this repo and then do `yarn` to install it.
2. Run `yarn db` to start docker container.
3. After that rename the `.env.example` in src and gaia folder to `.env`
4. Then do `yarn prisma generate` to start the generation, it will not happen and keep going on.
**Expected Behavior**
It should generate the typegraphql resolvers like it did in last version, you can test it by using the main branch which is still using older version

**Environment (please complete the following information):**

- OS: Arch Linux
- Node 15.9.0
- `typegraphql-prisma` version [e.g. 0.13.0]
- Prisma 2 version [2.20.1]
- TypeScript version (4.2.4)

**Additional Context**
Probably the way typegraphql was generating has changed.

**Comment by MichalLytek** [comment] 2021-04-08 09:16
Sorry but I'm unable to reproduce that when bumped the deps on the `examples/1-prototyping`.
There must be something weird in your setup.

>  the generation of typegraphql keeps going out infinitely.

What do you mean? Can you show some output, errors, more detailed info?

**Comment by Unbuttun** [comment] 2021-04-08 09:25
Hey, sorry about not able to put it in correct words - 
![yarn](https://user-images.githubusercontent.com/79936503/114002107-33f41b80-987a-11eb-870b-ebcf89bdd0a7.png)
it's like this, stays in such stage for super long(at least half an hour since i cancelled afterwards)

> Your dev branch does not contain typegraphql generator now.
I've fixed it now, it is there now in Dev branch

**Comment by MichalLytek** [comment] 2021-04-08 09:29
If I copy your schema into examples, it generates without any issues:
```
> prisma generate

Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.20.1) to ./packages/prisma in 77ms

✔ Generated TypeGraphQL integration to ./packages/type-graphql/tg in 1.23s
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from './packages/prisma'
const prisma = new PrismaClient()

```

Please create a new repository with a minimal reproducible code example. Not a half of your project with a complex setup. Otherwise I will have to close this issue.

**Comment by Unbuttun** [comment] 2021-04-08 09:31
oh, looks like i've messed it up somewhere, let me test it in empty repo, and if it's working, its my fault somewhere, then i will close that repo.

Thanks for giving your time and also thanks for maintaining typegraphql and this plugin. it makes grpahql so much easier

**Comment by Unbuttun** [comment] 2021-04-08 14:02
https://github.com/Unbuttun/typegraphql-prisma-test

hey @MichalLytek, I was able to figure out more. The generation works in yarn1 and while using npm, but stops when we use yarn2.

You can check the repo I mentioned in this comment, the yarn1 branch works through generation as it's using npm or yarn1 but the main branch which uses yarn2 does not generate.

Also the previous version did worked perfectly with yarn2. Maybe something that is specific for yarn2 got changed in latest version that is used while generating the resolvers.

**Comment by MichalLytek** [comment] 2021-04-08 14:04
> Also the previous version did worked perfectly with yarn2. Maybe something that is specific for yarn2 got changed in latest version that is used while generating the resolvers.

The new version has literally no change in the way how generator works - same lib name, same paths, nothing changed.

**Comment by Unbuttun** [comment] 2021-04-08 14:09
Do you know how I can enable more logs to show during generation? maybe that will make it easier.

also ill try find some way to handle it in yarn2 then close this issue. Changing the title accordingly

**Comment by Unbuttun** [comment] 2021-04-08 14:26
more info- as long as I enable node_modules linking in yarn2, the generator starts working again.

Most likely this part - 
https://github.com/MichalLytek/typegraphql-prisma/commit/76818e6afa8d3d099cdca8246c01510da606807a
`src/cli/prisma-generator.ts` this file is the one creating problems. 

is anyone of them trying to access node_modules in order to get info on prisma2 or something like that?

**Comment by MichalLytek** [comment] 2021-04-08 14:30
It works like that since the first version - trying to `require` generated prisma client folder in order to get transformed DMMF. In your case you have a dedicated folder for the prisma output, not `node_modules`.

**Comment by Unbuttun** [comment] 2021-04-08 14:38
Can we then give an option to let the generator find the location where the prisma is?

like 

```prisma
generator typegraphql {
  	provider = "typegraphql-prisma"
	clientLocation="../packages/prisma"
	output   = "../packages/type-graphql/tg"
}```

**Comment by MichalLytek** [comment] 2021-04-08 14:41
Why? Prisma parses `output` config or prisma client generator provider block.
Or at least it was parsing, but now with the env change it might not handle that properly... will check 👀

**Comment by MichalLytek** [comment] 2021-04-13 13:46
> Or at least it was parsing, but now with the env change it might not handle that properly... will check 👀

I've checked that and it's working without any issues.
For such Prisma schema:

```prisma
generator client {
  provider        = "prisma-client-js"
  binaryTargets   = ["windows", "debian-openssl-1.1.x"]
  output          = "../prisma/generated/client"
  previewFeatures = ["orderByRelation", "napi"]
}
```
the generator receives such generator info about prisma generator:

```js
{
    name: 'client',
    provider: { fromEnvVar: null, value: 'prisma-client-js' },
    output: {
      value: '/home/majkel/development/typegraphql-prisma/experiments/prisma/generated/client',
      fromEnvVar: null
    },
    binaryTargets: [ 'windows', 'debian-openssl-1.1.x' ],
    previewFeatures: [ 'orderByRelation', 'napi' ],
    config: {},
    isCustomOutput: true
  }
}
```

So it's still an absolute path to the directory, like it always was.

**Comment by Unbuttun** [comment] 2021-04-13 13:50
Can you tell a bit on how you were able to get this thing - 
```json
{
    name: 'client',
    provider: { fromEnvVar: null, value: 'prisma-client-js' },
    output: {
      value: '/home/majkel/development/typegraphql-prisma/experiments/prisma/generated/client',
      fromEnvVar: null
    },
    binaryTargets: [ 'windows', 'debian-openssl-1.1.x' ],
    previewFeatures: [ 'orderByRelation', 'napi' ],
    config: {},
    isCustomOutput: true
  }
}
```

I will try it with my test repo again

**Comment by MichalLytek** [comment] 2021-04-13 13:52
I've put `console.log` in `src/cli/prisma-generator.ts`:

![image](https://user-images.githubusercontent.com/10618781/114564047-40a8b300-9c70-11eb-9822-cccda998ad48.png)

**Comment by Unbuttun** [comment] 2021-04-13 13:53
and then run the generator in some example?

**Comment by MichalLytek** [comment] 2021-04-13 14:29
In this repo, only `experiments` project is connected to the `src` folder (run generator TS source code with ts-node). Examples are using npm-distributed packages.

**Comment by MichalLytek** [comment] 2021-04-28 14:52
Closing as it does not seems to be related with the changes made in Prisma generators.

Yarn 2 has many flaws and I don't recommend using it, especially with `typegraphql-prisma` 🔒

**Closed by MichalLytek** 2021-04-28 14:52 UTC
Labels: question
