### ISSUE TITLE
the generated types of `@id` columns in prisma schema should be ID not string

### ISSUE THREAD

**Issue by Unbuttun** [MichalLytek/typegraphql-prisma#96] opened 2021-04-10 17:32 UTC
**Describe the Bug**
The generated types of `@id` field in the schema should be ID from typegraphql/graphql.

for example for this model - 

```
model User {
  id        String   @id @default(uuid())
  createdAt DateTime @default(now())
}
```

the generated types are 
```ts
import * as TypeGraphQL from "type-graphql";

@TypeGraphQL.ObjectType({
  isAbstract: true
})
export class User {
  @TypeGraphQL.Field(_type => String, {
    nullable: false
  })
  id!: string;
**For this field :arrow_up_small:** 

  @TypeGraphQL.Field(_type => Date, {
    nullable: false
  })
  createdAt!: Date;
}
```

the types should be 
```ts
import * as TypeGraphQL from "type-graphql";

@TypeGraphQL.ObjectType({
  isAbstract: true
})
export class User {
  @TypeGraphQL.Field(_type => TypeGraphQL.ID, {
    nullable: false
  })
  id!: string;
**For this field :arrow_up_small:** 

  @TypeGraphQL.Field(_type => Date, {
    nullable: false
  })
  createdAt!: Date;
}


**To Reproduce**
It can already be found in the examples folder - 
https://github.com/MichalLytek/typegraphql-prisma/blob/main/examples/1-prototyping/prisma/generated/type-graphql/models/User.ts


**Expected Behavior**
The type of ID should be generated rather than String in order to let the graphql clients use it for caching, otherwise URQL complains and you need to manually set the ID, logically apollo client should do same

**Logs**
Sample of the error URQL sends when you don't have ID field.
```txt
Invalid key: The GraphQL query at the field at `Query.me` has a selection set, but no key could be generated for the data at this field.
You have to request `id` or `_id` fields for all selection sets or create a custom `keys` config for `UserResponse`.
Entities without keys will be embedded directly on the parent entity. If this is intentional, create a `keys` config for `UserResponse` that always returns null.
(Caused At: "Me" query)
https://bit.ly/2XbVrpR#15
```

**Environment (please complete the following information):**

- OS: Arch Linux
- Node (15.9.0)
- `typegraphql-prisma` version [0.12.0]
- Prisma 2 version [2.19.0]
- TypeScript version (4.2.4)

**Comment by MichalLytek** [comment] 2021-04-10 17:33
Duplicate of #26 🔒

**Closed by MichalLytek** 2021-04-10 17:33 UTC
