### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jlavric** [MichalLytek/typegraphql-prisma#212] opened 2021-11-26 12:19 UTC
**Describe the Bug**
I have added some models to schema and successfuly generate client (with emitTranspiledCode = false and simpleResolvers = true).
When I tried to run server I got:

```
/var/www/vhosts/flamboyant-khayyam.212-44-104-170.plesk.page/crm/src/generated/type-graphql/resolvers/inputs/WorkPositionCreateManyCreatedByInput.js:32
const TypeGraphQL = __importStar(require("type-graphql"));
                    ^

RangeError: Maximum call stack size exceeded
    at Object.<anonymous> (/var/www/vhosts/flamboyant-khayyam.212-44-104-170.plesk.page/crm/src/generated/type-graphql/resolvers/inputs/WorkPositionCreateManyCreatedByInput.js:32:21)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at Module.require (/usr/share/passenger/helper-scripts/node-loader.js:80:25)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/www/vhosts/flamboyant-khayyam.212-44-104-170.plesk.page/crm/src/generated/type-graphql/resolvers/inputs/WorkPositionCreateManyCreatedByInputEnvelope.js:33:48)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

Node.js v17.1.0
```
OS: CentOS Linux 7.9.2009 (Core)

Any idea how to approach this issue?

**Comment by MichalLytek** [comment] 2021-11-26 12:27
Can you try on Node 14 or 16?

**Comment by jlavric** [comment] 2021-11-26 14:53
On Node 16.3.0 I got the same message, but on 14.18.1 looks fine. I have now two setups running. I will post my updates and observations here. Im good with 14.x but it is getting old.
Thnx Janez

**Comment by MichalLytek** [comment] 2021-12-08 12:15
Sounds like duplicate of #10 #202 🔒

**Closed by MichalLytek** 2021-12-08 12:15 UTC

**Comment by lobanov-andrey** [comment] 2022-09-08 10:26
Added "node **--stack-size=2048** index.js" and it works;
Or "ts-node-dev **--stack_size=2048** index.ts"
