### ISSUE TITLE
The types of 'where.AND' are incompatible between these types.

### ISSUE THREAD

**Issue by DannyAziz** [MichalLytek/typegraphql-prisma#268] opened 2022-04-04 16:52 UTC
**Describe the Bug**
Getting type mismatches between Prisma and typegraphql but for the `AND` field

```
error TS2345: Argument of type 'FindManyUserArgs' is not assignable to parameter of type '{ select?: UserSelect; include?: UserInclude; where?: UserWhereInput; orderBy?: Enumerable<UserOrderByWithRelationInput>; cursor?: UserWhereUniqueInput; take?: number; skip?: number; distinct?: Enumerable<...>; }'.
  The types of 'where.AND' are incompatible between these types.
    Type 'UserWhereInput[]' is not assignable to type 'Enumerable<UserWhereInput>'.

24   const users = await prisma.user.findMany(data);
```

**Environment (please complete the following information):**

- OS: Macos
- Node 14.18.3
- `typegraphql-prisma` version: 0.19.2
- Prisma version 3.11.0
- TypeScript version 4.6.3

**Additional Context**
Related to #222

**Comment by MichalLytek** [comment] 2022-04-04 17:21
I think it's a duplicate of #222. It's the same recursive check issue. It does not matter if it's a `WhereInput` for `User` or `Foo`.

**Closed by MichalLytek** 2022-04-04 17:21 UTC
Labels: duplicate
