### ISSUE TITLE
Cannot find module '../outputs/Quill' Or Any Related Base Model

### ISSUE THREAD

**Issue by abstechnologydeveloper** [MichalLytek/typegraphql-prisma#455] opened 2024-06-15 16:55 UTC
I noticed that the generated files started showing that specific error in the screen below. It has really affected my works. I don't what to do. 
<img width="1440" alt="Screenshot 2024-06-15 at 17 54 38" src="https://github.com/MichalLytek/typegraphql-prisma/assets/129496648/e82f51b8-4324-4ec8-9d11-6866c0d3c9d1">
<img width="1440" alt="Screenshot 2024-06-15 at 17 54 50" src="https://github.com/MichalLytek/typegraphql-prisma/assets/129496648/08d458b6-54bb-4f46-b672-93bbb866095e">

**Comment by MichalLytek** [comment] 2024-06-15 18:15
Duplicate of #450 🔒

**Closed by MichalLytek** 2024-06-15 18:15 UTC
