### ISSUE TITLE
Add more field decorator options inside the prisma schema

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/typegraphql-prisma#21] opened 2020-10-22 14:03 UTC
It would be awesome to have a bit more control over how the CRUD resolvers are generated. For example there could be more options to the field decorator to include authorization like so:
```
model User {
  id     Int     @default(autoincrement()) @id
  /// @TypeGraphQL.field(name: "emailAddress")
  email  String  @unique
  /// @TypeGraphQL.field(authorized: ["User", "Admin"])
  posts  Post[]
}
```
Is this something you consider as a feature? I think this would greatly increase development speed.

**Comment by MichalLytek** [comment] 2020-10-22 15:31
Duplicate of #11 🔒

**Comment by MichalLytek** [comment] 2020-11-11 18:12
Actually, it's not a duplicate 😅 

#11 refers to crud resolvers methods, however fields or relations also might need to set up authorization or other custom decorators.

Reopening to implement the same enhance map pattern but for model fields, as well as for input types (class-validator validation?) 😉

**Comment by MichalLytek** [comment] 2020-12-03 15:51
First iteration done in `v0.9.1`:
https://github.com/MichalLytek/typegraphql-prisma/releases/tag/v0.9.1

Next release will focus on enhancing other output types and gonna allow to put decorators on the class itself, not only on its fields.

**Comment by MichalLytek** [comment] 2020-12-16 15:59
Second iteration is also done in `v0.9.2` 🚀 You can now add decorators for both model class itself as well as its fields:
```ts
const modelsEnhanceMap: ModelsEnhanceMap = {
  Director: {
    class: [Extensions({ isDirector: true })],
    fields: {
      movies: [Authorized()],
    },
  },
};
applyModelsEnhanceMap(modelsEnhanceMap);
```

Third iteration will allow to decorate other object types like the aggregate ones.

**Comment by CarlosBalladares** [comment] 2021-01-27 11:48
Are there any plans for a `applyInputTypesEnhanceMap`

**Comment by MichalLytek** [comment] 2021-01-27 11:50
@CarlosBalladares 
> Reopening to implement the same enhance map pattern but for model fields, as well as for input types

**Comment by MichalLytek** [comment] 2021-02-23 13:10
Quick update - we now have support for adding decorators to:
- crud resolvers
- output types (like `AggregateClient`)
- model types
- input types
- args types

The last part is adding decorators to relation resolvers 👀

**Comment by CarlosBalladares** [comment] 2021-02-23 13:12
awesome!!! 💯

**Comment by MichalLytek** [comment] 2021-03-03 12:33
Relation resolvers support has been added in 0dcc0f9d, so closing this one 🔒

**Closed by MichalLytek** 2021-03-03 12:33 UTC
Labels: enhancement
