### ISSUE TITLE
TypeError: graphql_fields_1.default is not a function

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/typegraphql-prisma#120] opened 2021-05-27 10:10 UTC
**Describe the Bug**
After generating the TypegraphQL classes a runtime error happens in all generated resolvers (custom ones still function):

`TypeError: graphql_fields_1.default is not a function`

The error does not appear in nestjs run logs or anything else, but gets packed inside the graphql response:

<img width="1582" alt="Bildschirmfoto 2021-05-27 um 11 14 37" src="https://user-images.githubusercontent.com/6214415/119806592-a1b7dd80-bee2-11eb-9ea4-e5a25143a9ff.png">

Not quite sure what's causing it, this is the corresponding code:

```js
const TypeGraphQL = require("type-graphql");
const graphql_fields_1 = require("graphql-fields");
const AggregateFeedItemArgs_1 = require("./args/AggregateFeedItemArgs");
const CreateFeedItemArgs_1 = require("./args/CreateFeedItemArgs");
const CreateManyFeedItemArgs_1 = require("./args/CreateManyFeedItemArgs");

// .....

    async feedItems(ctx, info, args) {
        const { _count } = helpers_1.transformFields(graphql_fields_1.default(info)); // THIS IS WHERE THE ERROR POINTS TO
        return helpers_1.getPrismaFromContext(ctx).feedItem.findMany({
            ...args,
            ...(_count && helpers_1.transformCountFieldIntoSelectRelationsCount(_count)),
        });
    }
```

The graphql-fields export looks good to me:

```js
module.exports = function graphqlFields(info) {
  var obj = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  var opts = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {
    processArguments: false
  };
  var fields = info.fieldNodes || info.fieldASTs;
  options.processArguments = opts.processArguments;
  options.excludedFields = opts.excludedFields || [];
  return fields.reduce(function (o, ast) {
    return flattenAST(ast, info, o);
  }, obj) || {};
};
```

**To Reproduce**
Generate resolvers and query the nodes.

**Expected Behavior**
Shouldn't throw a runtime error and serve the correct response.

**Environment:**

- OS: macOS 10.15.7
- Node 14.6.0
- `typegraphql-prisma` version 0.14.3
- Prisma 2 version 2.23.0
- TypeScript version 4.3.2

**Additional context:**
I am using this with nestjs, maybe this is some node issue or something, I don't have any pointer to where the problem may be, since everything seems to be in check.

**Comment by MichalLytek** [comment] 2021-05-27 10:25
Duplicate of #118 🔒 
Just use `"esModuleInterop": true`. I will write that in readme soon.

**Closed by MichalLytek** 2021-05-27 10:25 UTC
