### ISSUE TITLE
Failed to import on non node modules folder on Windows

### ISSUE THREAD

**Issue by shtse8** [MichalLytek/typegraphql-prisma#309] opened 2022-07-16 18:38 UTC
It works well in node module folder.
but failed to import in non node module folder on Windows.

### for setting:
```
generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "./prisma/generated/type-graphql"
}
```
```
generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "./prisma/generated/type-graphql"
  emitTranspiledCode = true
}
```

### result:

```
 ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'                                                                                                        02:35:35

  at new NodeError (node:internal/errors:372:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
  at defaultResolve (node:internal/modules/esm/resolve:1200:3)
  at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
  at link (node:internal/modules/esm/module_job:78:36)

[nitro] [dev] [uncaughtException] NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for parameter #2 of 'aggregateArticle' of 'ArticleCrudResolver' class.
    at Object.findType (D:\project\node_modules\type-graphql\dist\helpers\findType.js:19:15)
    at Object.getParamInfo (D:\project\node_modules\type-graphql\dist\helpers\params.js:10:49)
    at D:\project\node_modules\type-graphql\dist\decorators\Args.js:12:25
    at file:///D:/project/.nuxt/dev/index.mjs:1185:64
    at __decorateClass$1c (file:///D:/project/.nuxt/dev/index.mjs:1180:24)
    at file:///D:/project/.nuxt/dev/index.mjs:1271:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)

```

tsconfig.json
```json
{
  "extends": "./.nuxt/tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "target": "esnext",
    "lib": ["esnext", "esnext.asynciterable"],
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true
  },
}
```

**Comment by MichalLytek** [comment] 2022-07-27 10:41
The generator only works with Common JS.
Disable `emitTranspiledCode` and compile the generated source code by yourself.

**Comment by Jay-flow** [comment] 2022-11-22 23:42
I have the same issue.

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2018",
    "lib": ["dom", "dom.iterable", "esnext", "esnext.asynciterable"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "strictPropertyInitialization": false,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "jsx": "preserve",
    "incremental": true,
    "emitDecoratorMetadata": false,
    "noUnusedLocals": false,
    "experimentalDecorators": true,
    "isolatedModules": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Comment by MichalLytek** [comment] 2022-12-12 12:58
Closing as duplicate of #13 🔒

**Closed by MichalLytek** 2022-12-12 12:58 UTC
Labels: question
