### ISSUE TITLE
Input Object type <ONLYIDSMODEL>UpdateManyDataInput must define one or more fields

### ISSUE THREAD

**Issue by jakegiri** [MichalLytek/typegraphql-prisma#199] opened 2021-10-17 23:35 UTC
**NOTE** 
This bug is already but under nexus-plugin-prisma mentioned in the following below links. But the bug is same for typegraphql-prisma. So i recreated it under typegraphql-prisma

1. https://github.com/graphql-nexus/nexus-plugin-prisma/issues/648
2. https://github.com/graphql-nexus/nexus-plugin-prisma/issues/801

**THE BUG**

DESCRIPTION
If a model doesn't have any scalar fields (only own id and other relation ids), like in the RolesAdministratorsMapping, then some types generated for update many resolvers of this model are empty. So when I try to run my server I get the input type errors that you can see in the screenshot

**Screenshots**

1. schema.prisma
     ![image](https://user-images.githubusercontent.com/24270559/137648284-26e0f3d7-0716-46a9-9630-db2c548ee6b4.png)

2.  (empty field generated by typegraphql-prisma ) RolesAdministratorsMappingUpdateManyMutationInput.ts** 

     ![image](https://user-images.githubusercontent.com/24270559/137648825-c9e58294-81eb-4125-b680-7b8ea097a440.png)

##################################
##################################

**THE FIX  JUST AS AN WORKAROUND**

##################################
##################################

- **if you just add a dummy scalar field to the model, everything works fine**
      ![image](https://user-images.githubusercontent.com/24270559/137648630-7b4efb0b-b2ef-4c15-988a-c22545f5767d.png)

- **SCREENSHOT after adding dummy scalar**
      ![image](https://user-images.githubusercontent.com/24270559/137648812-2744911e-aa46-40b9-8f7c-d1ad498376da.png)

**Comment by MichalLytek** [comment] 2021-10-18 05:42
Duplicate of #19 🔒

**Closed by MichalLytek** 2021-10-18 05:42 UTC

**Comment by jakegiri** [comment] 2021-10-19 01:09
@MichalLytek Thanks
