### ISSUE TITLE
can we support baisc type in update?

### ISSUE THREAD

**Issue by zhuozhongcao** [MichalLytek/typegraphql-prisma#52] opened 2021-01-27 14:45 UTC
for example, this is generated update args

`
export declare class AccountSecretUpdateWithoutUserInput {
    id?: IntFieldUpdateOperationsInput | undefined;
    phone?: NullableStringFieldUpdateOperationsInput | undefined;
}
`
when we use this to update , we must write
`
{ phone: { set: $phone } } 
`

can we support this in mutation(update):
`
export declare class AccountSecretUpdateWithoutUserInput {
    id?: IntFieldUpdateOperationsInput | number | undefined;
    phone?: NullableStringFieldUpdateOperationsInput | string  | undefined;
}

{ phone: $phone }
`

**Comment by MichalLytek** [comment] 2021-01-27 14:46
Duplicate of #32 🔒

**Closed by MichalLytek** 2021-01-27 14:46 UTC
