### ISSUE TITLE
performance issue +100 table

### ISSUE THREAD

**Issue by dnnnew** [MichalLytek/typegraphql-prisma#162] opened 2021-08-17 10:42 UTC
Hi, 

I'm using typegraphql-prisma for 134 tables. 
Generation time is 60sec, and server start time is ~20-~30sec. 
It's bit hard to development in each change. 

Is there any improvement for this. 

Thanks.

**Comment by MichalLytek** [comment] 2021-08-17 11:01
> Is there any improvement for this.

No, there's not.

Duplicate of #10 🔒

**Closed by MichalLytek** 2021-08-17 11:01 UTC
