### ISSUE TITLE
Setting default values for mutation inputs

### ISSUE THREAD

**Issue by Falco-Boehnke** [MichalLytek/typegraphql-prisma#211] opened 2021-11-25 13:26 UTC
**Is your feature request related to a problem? Please describe.**
Currently I seem to be unable to set a default value for mutations. Say you have 'CreateUser' and a field called 'isArchived', currently it seems the applyInputTypesEnhanceMap does not allow me to set a default value for fields. 

**Describe the solution you'd like**
I would like to granularly set defaultValues for certain fields on Mutations. Either through the prisma schema or the custom decorator logic. 

**Describe alternatives you've considered**
A middleware that allows me to inject values into the graphql query before it reaches the resolver. Tried it in a middleware, changing the args object, but the resolver rejected the changes every time (Cannot read undefined of title, despite object being fully populated)

**Additional context**
```
 applyInputTypesEnhanceMap({
     UserCreateInput: {
         fields: {
             isArchived: [Field({ defaultValue: true, nullable: false })],
         },
     },
 });
```

**Comment by MichalLytek** [comment] 2021-11-25 13:28
Duplicate of #139 🔒

**Closed by MichalLytek** 2021-11-25 13:28 UTC
