### ISSUE TITLE
Prisma models made up of only relations breaks prisma generator

### ISSUE THREAD

**Issue by Atlinx** [MichalLytek/typegraphql-prisma#289] opened 2022-05-20 19:00 UTC
**Describe the Bug**
If you declare in a `schema.prisma` file models that only contain relations and an id, the type-graphql prisma generator will fail.

**To Reproduce**
1. Use this `schema.prisma`
```prisma
generator client {
  provider = "prisma-client-js"
}

generator typegraphql {
  provider = "typegraphql-prisma"
}

datasource db {
  provider = "mongodb"
  url      = env("DB_URL")
}

model User {
  id              String              @id @default(auto()) @map("_id") @db.ObjectId
  email           String              
  roles           UserRole[]
}

model UserRole {
  id       String       @id @default(auto()) @map("_id") @db.ObjectId
  test     String
  type     UserRoleType @relation(fields: [typeId], references: [id])
  typeId   String
  member   User         @relation(fields: [memberId], references: [id])
  memberId String
}

model UserRoleType {
  id          String     @id @default(auto()) @map("_id") @db.ObjectId
  name        String     @unique
  roles       UserRole[]
  permissions String[]
```
2. Have everything else configured correctly for prisma generation. ( )
3. Run `npx prisma generate`
4. See this error
```
Error: Some errors occurred while generating GraphQL Schema:
Input Object type UserRoleUpdateManyMutationInput must define one or more fields.
```

**Expected Behavior**
The type-graphql prisma generator should work successfully with no errors.

**Environment (please complete the following information):**

- OS: Windows
- Node: v17.6.0
- Package version: v1.1.1
- TypeScript version v4.6.4

**Comment by MichalLytek** [comment] 2022-05-20 20:00
Duplicate of #19 🔒

**Closed by MichalLytek** 2022-05-20 20:00 UTC
