### ISSUE TITLE
many to many relationship

### ISSUE THREAD

**Issue by ZobairQ** [MichalLytek/typegraphql-prisma#76] opened 2021-03-10 19:01 UTC
**Describe the Bug**
If you have a many to many relationship where you have a table between two tables that only hold foreign_keys, prisma will create a model for that. Typegraphql will then try to create a mutation for that, but there won't be any input data. When trying to start the application you get an error stating that your mutationInput should atleast have a field.

**To Reproduce**
To reproduce this try to create  three tables in your sql. T1, T2 and T3. T1 and T3 are ordinary tables and T2 contains only T1's pk and T3' pk.

**Expected Behavior**
It shouldn't create mutation for table T2 since it's just a table to keep track of the relations with two other tables.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occurred.

**Environment (please complete the following information):**

- OS: [MAC OSX]
- Node (e.g. 14.16.0)
- `typegraphql-prisma` version [0.11.2]
- Prisma 2 version [e.g. 2.18.0]
- TypeScript version (e.g. 4.2.2)

**Comment by MichalLytek** [comment] 2021-03-10 19:03
Duplicate of #19 🔒

**Closed by MichalLytek** 2021-03-10 19:03 UTC
