### ISSUE TITLE
Use Typegraphql's useMiddleware() function?

### ISSUE THREAD

**Issue by sandipndev** [MichalLytek/typegraphql-prisma#15] opened 2020-10-12 15:58 UTC
How can I implement authorization scope for different users? In plain typegraphql a simple `useMiddleware` function could solve it but is there a way to implement the same using typegraphql-prisma while still having the same query/mutation structure?

**Comment by MichalLytek** [comment] 2020-10-12 15:59
Duplicate of #11

**Closed by MichalLytek** 2020-10-12 15:59 UTC
