### ISSUE TITLE
Incompatible types between prisma and typegraphql-prisma

### ISSUE THREAD

**Issue by jorge-gutierrez** [MichalLytek/typegraphql-prisma#413] opened 2023-08-10 23:41 UTC
**Describe the Bug**
Hi, after upgrading to Prisma version 5 and generating the corresponding types, when I run the project, I get the following errors 
errors:

**To Reproduce**
This is my resolver:
![image](https://github.com/MichalLytek/typegraphql-prisma/assets/55706638/6b7e211d-1e89-41f2-b287-1591a3296dc6)

This is my service:
![image](https://github.com/MichalLytek/typegraphql-prisma/assets/55706638/acc50bf1-8d4e-4f38-9654-b51fc5c25e5a)

This is my schema:
![image](https://github.com/MichalLytek/typegraphql-prisma/assets/55706638/c4aee24c-33f6-4268-89c0-28fd70880899)

**Expected Behavior**
The types should match and be compatible.

**Logs**
![image](https://github.com/MichalLytek/typegraphql-prisma/assets/55706638/acbd72dc-e5ea-4d77-ad5f-c7ed864410cc)
![image](https://github.com/MichalLytek/typegraphql-prisma/assets/55706638/1ab0192b-21e2-4003-b0ea-60855b0b2860)
![image](https://github.com/MichalLytek/typegraphql-prisma/assets/55706638/44d56383-ea27-4c50-8cf3-018ffbff96c6)

**Environment (please complete the following information):**

- OS: Windows 10 22H2
- Node: 18.12.1
- `typegraphql-prisma` 0.27.0
- Prisma version 5.0.0
- TypeScript version 5.1.6
- `typegraphql-nest` 0.6.0

**Comment by MichalLytek** [comment] 2023-08-11 06:42
Duplicate of #406 🔒

**Closed by MichalLytek** 2023-08-11 06:42 UTC
