### ISSUE TITLE
Reserved words as association model will generate invalid typescript

### ISSUE THREAD

**Issue by richardwu** [MichalLytek/typegraphql-prisma#183] opened 2021-09-16 03:09 UTC
**Describe the Bug**

When including associations of models with a reserved keyword name, the TS (JS even w/ transpiled code) generated will not compile.

**To Reproduce**
A quick guide how to reproduce the bug.

Include the following in your schema:
```

model Class {
  id     Int  @id
  user   User @relation(fields: [userId], references: [id])
  userId Int
}

model User {
  id      Int     @id @default(autoincrement())
  classes Class[]
}
```

This will generate the following code: 
```ts
// ClassRelationsResolver.ts
import * as TypeGraphQL from "type-graphql";
import { Class } from "../../../models/Class";
import { User } from "../../../models/User";
import { transformFields, getPrismaFromContext, transformCountFieldIntoSelectRelationsCount } from "../../../helpers";

@TypeGraphQL.Resolver(_of => Class)
export class ClassRelationsResolver {
  @TypeGraphQL.FieldResolver(_type => User, {
    nullable: false
  })
  async user(@TypeGraphQL.Root() class: Class, @TypeGraphQL.Ctx() ctx: any): Promise<User> {
    return getPrismaFromContext(ctx).class.findUnique({
      where: {
        id: class.id,
      },
    }).user({});
  }
}
```
where `class: Class` will throw an error because `class` is a reserved keyword.

```
generated/typegraphql-prisma/resolvers/relations/Class/ClassRelationsResolver.ts:11:34 - error TS1359: Identifier expected. 'class' is a reserved word that cannot be used here.

11   async user(@TypeGraphQL.Root() class: Class, @TypeGraphQL.Ctx() ctx: any): Promise<User> {
                                    ~~~~~
```

**Expected Behavior**

Generated arg name that is a reserved keyword should be substituted.

**Environment (please complete the following information):**

- OS: [e.g. Windows 10 21H1]
- Node 15.0.1
- `typegraphql-prisma` version 0.16.0
- Prisma version: 3.0.2
- TypeScript version: 4.4.3

**Comment by MichalLytek** [comment] 2021-09-16 06:42
Duplicate of #127 🔒 

You need to expose your model under a different name:
https://prisma.typegraphql.com/docs/advanced/renaming-model

**Closed by MichalLytek** 2021-09-16 06:42 UTC
